### ISSUE TITLE
The renewal of Intellisense does not work after an adjustment.

### ISSUE THREAD

**Issue by Timbuktu1982** [DEVSENSE/phptools-docs#182]
Hello all,
first of all I would like to thank you for the great tool.

But I do have one problem.

I start vscode and after a few seconds the extension flags all errors/warnings. Everything is fine up to here.
I solve one of the displayed problems, but the error error/warning does not disappear.
When I restart the window, the error/warning has correctly disappeared.

What is wrong?

THX

**Comment by jakubmisek** [comment]
Thank you @Timbuktu1982 ! 

It looks like a bug, the problem should disappear. Does it happen in any file in your workspace?

**Comment by Timbuktu1982** [comment]
I have tried that. I waited a few minutes and nothing happened. However, when I reload the window, it updates correctly (approximately after 10 seconds).

**Comment by jakubmisek** [comment]
thank you, we'll try to repro the issue and see

**Comment by Timbuktu1982** [comment]
before updating (correct note): 
![grafik](https://user-images.githubusercontent.com/47846931/196703754-ecb5a8cb-9624-451a-a65d-1c0ac6bb4973.png)

after updating (normally the note should have been gone):
![grafik](https://user-images.githubusercontent.com/47846931/196704145-1d051c71-6025-498e-b511-b2258d5de1a7.png)

(same with errors and warnings)

**Comment by Timbuktu1982** [comment]
note: when i reload the window, the note is removed correctly

**Comment by Timbuktu1982** [comment]
Excuse me, here is the relevant line in the problem display (not removed after updating, only removed after window reload)...

![grafik](https://user-images.githubusercontent.com/47846931/196705047-7aa46889-b8b1-486d-a178-182b64fd9f39.png)

**Comment by Timbuktu1982** [comment]
> so the errors are not updating like this, right?
> 
> ![vsc-update-problems](https://user-images.githubusercontent.com/842150/196700725-73e73fc8-69c9-4714-b5a9-100ce1be2cff.gif) [ ![vsc-update-problems](https://user-images.githubusercontent.com/842150/196700725-73e73fc8-69c9-4714-b5a9-100ce1be2cff.gif) ](https://user-images.githubusercontent.com/842150/196700725-73e73fc8-69c9-4714-b5a9-100ce1be2cff.gif) [ ](https://user-images.githubusercontent.com/842150/196700725-73e73fc8-69c9-4714-b5a9-100ce1be2cff.gif)

Here the same, when i use your example (no error message displayed)
![grafik](https://user-images.githubusercontent.com/47846931/196707156-464fe96f-321e-41ea-ba86-848d5484f7c8.png)

**Comment by jakubmisek** [comment]
thank you for the details!

Ok, it seems the problems are not being updated at all.

Is it a local workspace, or a remote workspace?

**Comment by Timbuktu1982** [comment]
Hi Jakub,
local workspace only at the moment...

**Comment by jakubmisek** [comment]
Right, it seems the errors don't update at all for you. May I ask:

- Do you have any errors in Developer Console (Help -> Toggle Developer Tools -> `Console` tab) (anything red?)
- Anything unexpected in Output - PHP Language Server?
    ![image](https://user-images.githubusercontent.com/842150/196902852-73b5b15e-bfbc-4db5-80d0-b62379e7d412.png)
- isn't the loading in the status bar still spinning?
    ![image](https://user-images.githubusercontent.com/842150/196903076-2f488714-2782-403b-9095-b26c6082f066.png)
- high CPU usage?

Thank you!

**Comment by Timbuktu1982** [comment]
>     * Do you have any errors in Developer Console (Help -> Toggle Developer Tools -> `Console` tab) (anything red?)

Yes, a lot of, but not all from php tools...

INFO Electron sandbox mode is enabled!
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.azure-repos' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.remotehub' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'dbaeumer.vscode-eslint' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:318  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-github-issue-notebooks' wants API proposal 'localization' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:330 CRITI Extension 'vscode.typescript-language-features' wants API proposal 'workspaceEditIsRefactoring' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
7log.ts:312  INFO [MehediDracula.php-namespace-resolver]: Das Menüelement verweist auf den gleichen Befehl wie der Standard- und der Alternativbefehl.
3log.ts:312  INFO [phproberto.vscode-php-getters-setters]: Das Menüelement verweist auf den gleichen Befehl wie der Standard- und der Alternativbefehl.
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///snap/code-insiders/1131/usr/share/code-insiders/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///home/timbuktu/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221018/syntaxes/JavaScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:47
R @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:240
await in _getOrCreateGrammarFactory (async)
createTokenizationSupport @ abstractTextMateService.ts:264
_create @ tokenizationRegistry.ts:146
resolve @ tokenizationRegistry.ts:140
getOrCreate @ tokenizationRegistry.ts:72
(anonymous) @ abstractTextMateService.ts:165
_handle @ extensionsRegistry.ts:143
acceptUsers @ extensionsRegistry.ts:134
_handleExtensionPoint @ abstractExtensionService.ts:1267
_doHandleExtensionPoints @ abstractExtensionService.ts:1200
_startLocalExtensionHost @ electronExtensionService.ts:592
await in _startLocalExtensionHost (async)
_scanAndHandleExtensions @ electronExtensionService.ts:554
_initialize @ abstractExtensionService.ts:759
await in _initialize (async)
(anonymous) @ electronExtensionService.ts:115
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1163
(anonymous) @ electronExtensionService.ts:114
Promise.then (async)
qc @ electronExtensionService.ts:112
y @ sandboxExtensionService.ts:12
_createInstance @ instantiationService.ts:117
_createServiceInstance @ instantiationService.ts:243
_createServiceInstanceWithOwner @ instantiationService.ts:232
_createAndCacheServiceInstance @ instantiationService.ts:221
_safeCreateAndCacheServiceInstance @ instantiationService.ts:161
_getOrCreateServiceInstance @ instantiationService.ts:145
get @ instantiationService.ts:61
initLayout @ layout.ts:229
(anonymous) @ workbench.ts:149
invokeFunction @ instantiationService.ts:68
startup @ workbench.ts:141
open @ desktop.main.ts:120
await in open (async)
ie @ desktop.main.ts:386
d.load.configureDeveloperSettings @ workbench.js:2793
(anonymous) @ workbench.js:2664
a._invokeFactory @ workbench.js:1460
a.complete @ workbench.js:1470
a._onModuleComplete @ workbench.js:2100
a._onModuleComplete @ workbench.js:2112
a._resolve @ workbench.js:2057
a.defineModule @ workbench.js:1700
h @ workbench.js:2150
(anonymous) @ workbench.common.main.ts:145
(anonymous) @ fake:1
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///snap/code-insiders/1131/usr/share/code-insiders/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///home/timbuktu/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221018/syntaxes/JavaScript.tmLanguage.json
register @ TMScopeRegistry.ts:47
R @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:240
await in _getOrCreateGrammarFactory (async)
createTokenizationSupport @ abstractTextMateService.ts:264
_create @ tokenizationRegistry.ts:146
resolve @ tokenizationRegistry.ts:140
getOrCreate @ tokenizationRegistry.ts:72
(anonymous) @ abstractTextMateService.ts:165
_handle @ extensionsRegistry.ts:143
acceptUsers @ extensionsRegistry.ts:134
_handleExtensionPoint @ abstractExtensionService.ts:1267
_doHandleExtensionPoints @ abstractExtensionService.ts:1200
_startLocalExtensionHost @ electronExtensionService.ts:592
await in _startLocalExtensionHost (async)
_scanAndHandleExtensions @ electronExtensionService.ts:554
_initialize @ abstractExtensionService.ts:759
await in _initialize (async)
(anonymous) @ electronExtensionService.ts:115
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1163
(anonymous) @ electronExtensionService.ts:114
Promise.then (async)
qc @ electronExtensionService.ts:112
y @ sandboxExtensionService.ts:12
_createInstance @ instantiationService.ts:117
_createServiceInstance @ instantiationService.ts:243
_createServiceInstanceWithOwner @ instantiationService.ts:232
_createAndCacheServiceInstance @ instantiationService.ts:221
_safeCreateAndCacheServiceInstance @ instantiationService.ts:161
_getOrCreateServiceInstance @ instantiationService.ts:145
get @ instantiationService.ts:61
initLayout @ layout.ts:229
(anonymous) @ workbench.ts:149
invokeFunction @ instantiationService.ts:68
startup @ workbench.ts:141
open @ desktop.main.ts:120
await in open (async)
ie @ desktop.main.ts:386
d.load.configureDeveloperSettings @ workbench.js:2793
(anonymous) @ workbench.js:2664
a._invokeFactory @ workbench.js:1460
a.complete @ workbench.js:1470
a._onModuleComplete @ workbench.js:2100
a._onModuleComplete @ workbench.js:2112
a._resolve @ workbench.js:2057
a.defineModule @ workbench.js:1700
h @ workbench.js:2150
(anonymous) @ workbench.common.main.ts:145
(anonymous) @ fake:1
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///snap/code-insiders/1131/usr/share/code-insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///home/timbuktu/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221018/syntaxes/TypeScript.tmLanguage.json
register @ TMScopeRegistry.ts:47
R @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:240
await in _getOrCreateGrammarFactory (async)
createTokenizationSupport @ abstractTextMateService.ts:264
_create @ tokenizationRegistry.ts:146
resolve @ tokenizationRegistry.ts:140
getOrCreate @ tokenizationRegistry.ts:72
(anonymous) @ abstractTextMateService.ts:165
_handle @ extensionsRegistry.ts:143
acceptUsers @ extensionsRegistry.ts:134
_handleExtensionPoint @ abstractExtensionService.ts:1267
_doHandleExtensionPoints @ abstractExtensionService.ts:1200
_startLocalExtensionHost @ electronExtensionService.ts:592
await in _startLocalExtensionHost (async)
_scanAndHandleExtensions @ electronExtensionService.ts:554
_initialize @ abstractExtensionService.ts:759
await in _initialize (async)
(anonymous) @ electronExtensionService.ts:115
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1163
(anonymous) @ electronExtensionService.ts:114
Promise.then (async)
qc @ electronExtensionService.ts:112
y @ sandboxExtensionService.ts:12
_createInstance @ instantiationService.ts:117
_createServiceInstance @ instantiationService.ts:243
_createServiceInstanceWithOwner @ instantiationService.ts:232
_createAndCacheServiceInstance @ instantiationService.ts:221
_safeCreateAndCacheServiceInstance @ instantiationService.ts:161
_getOrCreateServiceInstance @ instantiationService.ts:145
get @ instantiationService.ts:61
initLayout @ layout.ts:229
(anonymous) @ workbench.ts:149
invokeFunction @ instantiationService.ts:68
startup @ workbench.ts:141
open @ desktop.main.ts:120
await in open (async)
ie @ desktop.main.ts:386
d.load.configureDeveloperSettings @ workbench.js:2793
(anonymous) @ workbench.js:2664
a._invokeFactory @ workbench.js:1460
a.complete @ workbench.js:1470
a._onModuleComplete @ workbench.js:2100
a._onModuleComplete @ workbench.js:2112
a._resolve @ workbench.js:2057
a.defineModule @ workbench.js:1700
h @ workbench.js:2150
(anonymous) @ workbench.common.main.ts:145
(anonymous) @ fake:1
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///snap/code-insiders/1131/usr/share/code-insiders/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///home/timbuktu/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221018/syntaxes/TypeScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:47
R @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:240
await in _getOrCreateGrammarFactory (async)
createTokenizationSupport @ abstractTextMateService.ts:264
_create @ tokenizationRegistry.ts:146
resolve @ tokenizationRegistry.ts:140
getOrCreate @ tokenizationRegistry.ts:72
(anonymous) @ abstractTextMateService.ts:165
_handle @ extensionsRegistry.ts:143
acceptUsers @ extensionsRegistry.ts:134
_handleExtensionPoint @ abstractExtensionService.ts:1267
_doHandleExtensionPoints @ abstractExtensionService.ts:1200
_startLocalExtensionHost @ electronExtensionService.ts:592
await in _startLocalExtensionHost (async)
_scanAndHandleExtensions @ electronExtensionService.ts:554
_initialize @ abstractExtensionService.ts:759
await in _initialize (async)
(anonymous) @ electronExtensionService.ts:115
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1163
(anonymous) @ electronExtensionService.ts:114
Promise.then (async)
qc @ electronExtensionService.ts:112
y @ sandboxExtensionService.ts:12
_createInstance @ instantiationService.ts:117
_createServiceInstance @ instantiationService.ts:243
_createServiceInstanceWithOwner @ instantiationService.ts:232
_createAndCacheServiceInstance @ instantiationService.ts:221
_safeCreateAndCacheServiceInstance @ instantiationService.ts:161
_getOrCreateServiceInstance @ instantiationService.ts:145
get @ instantiationService.ts:61
initLayout @ layout.ts:229
(anonymous) @ workbench.ts:149
invokeFunction @ instantiationService.ts:68
startup @ workbench.ts:141
open @ desktop.main.ts:120
await in open (async)
ie @ desktop.main.ts:386
d.load.configureDeveloperSettings @ workbench.js:2793
(anonymous) @ workbench.js:2664
a._invokeFactory @ workbench.js:1460
a.complete @ workbench.js:1470
a._onModuleComplete @ workbench.js:2100
a._onModuleComplete @ workbench.js:2112
a._resolve @ workbench.js:2057
a.defineModule @ workbench.js:1700
h @ workbench.js:2150
(anonymous) @ workbench.common.main.ts:145
(anonymous) @ fake:1
console.ts:137 [Extension Host] ApplicationInsights:unable to read app version:  [{…}] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager [{…}] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
mainThreadExtensionService.ts:79 [[object Object]]Failed to created templates directory /home/timbuktu/.config/Code/User/phpGettersSetters
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:626
deliver @ event.ts:828
fire @ event.ts:789
fire @ ipc.net.ts:646
ne.onmessage @ localProcessExtensionHost.ts:615
mainThreadExtensionService.ts:80 Error: Failed to created templates directory /home/timbuktu/.config/Code/User/phpGettersSetters
	at /home/timbuktu/.vscode-insiders/extensions/phproberto.vscode-php-getters-setters-1.2.3/out/TemplatesManager.js:47:23
	at FSReqCallback.oncomplete (node:fs:188:23)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:626
deliver @ event.ts:828
fire @ event.ts:789
fire @ ipc.net.ts:646
ne.onmessage @ localProcessExtensionHost.ts:615
console.ts:137 [Extension Host] ApplicationInsights:unable to read app version:  [{…}] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager [{…}] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
log.ts:324   ERR [geyao.html-snippets]: Unbekannte Sprache in "contributes.html-snippets.language". Angegebener Wert: vue-html
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager ['caa9fc5b-bf66-4a4b-a9cd-0a5973a62095'] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager ['caa9fc5b-bf66-4a4b-a9cd-0a5973a62095'] (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] rejected promise not handled within 1 second: EntryNotFound (FileSystemError): Die nicht vorhandene Datei „vscode-userdata:/home/timbuktu/.config/Code - Insiders/User/globalStorage/xshrim.txt-syntax“ kann nicht gelöscht werden. (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:626
deliver @ event.ts:828
fire @ event.ts:789
fire @ ipc.net.ts:646
ne.onmessage @ localProcessExtensionHost.ts:615
console.ts:137 [Extension Host] stack trace: EntryNotFound (FileSystemError): Die nicht vorhandene Datei „vscode-userdata:/home/timbuktu/.config/Code - Insiders/User/globalStorage/xshrim.txt-syntax“ kann nicht gelöscht werden.
	at Xt._handleError (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:93:29726)
	at Object.delete (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:93:29010) (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:626
deliver @ event.ts:828
fire @ event.ts:789
fire @ ipc.net.ts:646
ne.onmessage @ localProcessExtensionHost.ts:615
log.ts:324   ERR Die nicht vorhandene Datei „vscode-userdata:/home/timbuktu/.config/Code - Insiders/User/globalStorage/xshrim.txt-syntax“ kann nicht gelöscht werden.: EntryNotFound (FileSystemError): Die nicht vorhandene Datei „vscode-userdata:/home/timbuktu/.config/Code - Insiders/User/globalStorage/xshrim.txt-syntax“ kann nicht gelöscht werden.
	at Xt._handleError (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:93:29726)
	at Object.delete (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:93:29010)
console.ts:137 [Extension Host] [vscode-icons] v12.0.0 activated! (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] model completion cache refreshed :: 0 (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] completionCache refreshed :: /var/www/html/flex-container-plugins/origin/flex-chat , size:: 0 (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))
console.ts:137 [Extension Host] addon completionCache refreshed :: /var/www/html/flex-container-plugins/origin/flex-chat , size:: 0 (at console.<anonymous> (/snap/code-insiders/1131/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:142190))

**Comment by Timbuktu1982** [comment]
> * Anything unexpected in Output - PHP Language Server?

Processing include path: 'file:///var/www/html/flex-container' ...

PHP Tools server started.
    PID: 208033
    Processing files: .php; .phtml; .jsf

**Comment by Timbuktu1982** [comment]
> * isn't the loading in the status bar still spinning?
no

![grafik](https://user-images.githubusercontent.com/47846931/196914966-b8d45d8e-efa0-494c-b348-e051bdd8d0c1.png)

**Comment by Timbuktu1982** [comment]
> * high CPU usage?

no, i have a high configured system

![grafik](https://user-images.githubusercontent.com/47846931/196915349-371f9ddc-a14d-4d4f-9037-96bfbfb4b200.png)

**Comment by jakubmisek** [comment]
> Yes, a lot of, but not all from php tools...

It looks like there are some issues with VSC itself. This may cause something ...

Do PHP code completion and tooltips work normally?

**Comment by Timbuktu1982** [comment]
Yes, this things working fine...

For Information: I use vsc insiders. Is this a problem?

**Comment by jakubmisek** [comment]
> For Information: I use vsc insiders. Is this a problem?

it may break some features - we'll try the latest insiders as well if it happens to us

**Comment by jakubmisek** [comment]
@Timbuktu1982 even in Insiders, the problems get updated immediately.

I've noticed, you're on macOS/Linux, right? We're testing primarily on Windows (which has a different filesystem API)

**Comment by Timbuktu1982** [comment]
Hi Jakub,

yes, i use linux...

Here more information about my configuration:

- linux ubuntu 22.10 latest
- node v18.7.0 (if this has relevance)
- php 7.4.32 (also testet in 8.1.11, same problem)
- vscode insiders latest
- vscode used plugins for php
-- php cs fixer
-- PHP Getters & Setters
-- PHP Namespace Resolver
-- PHPDoc Generator

**Comment by jakubmisek** [comment]
Thanks, we'll test that within a day. 

_php_ does not matter, we don't use it,

Other extensions might cause some incompatibilities tho - we'll test them as well.

- Is your project based on some publically available framework?

**Comment by Timbuktu1982** [comment]
> * Is your project based on some publically available framework?

no, its a private framework from my company

**Comment by jakubmisek** [comment]
> no, its a private framework from my company
ok, I guess it's not what's causing the issue.

**Comment by Timbuktu1982** [comment]
> ok, I guess it's not what's causing the issue.

I can't imagine either

**Comment by jakubmisek** [comment]
We've tested the same configuration, but still no issues :/

(only some errors with _phpGettersSetters_ - which btw its functionality is [included in PHP tools](https://docs.devsense.com/en/vscode/editor/code-actions#getters-and-setters))

**Q:** May I send you an "insider" build of PHP Tools with more detailed diagnostics, so we get more information?

**Comment by Timbuktu1982** [comment]
Hi Jakub,

thanks you for your commitment ...

> (only some errors with _phpGettersSetters_ - which btw its functionality is [included in PHP tools](https://docs.devsense.com/en/vscode/editor/code-actions#getters-and-setters))
ok, i want to uninstall this plugin

> Q: May I send you an "insider" build of PHP Tools with more detailed diagnostics, so we get more information?
good idea... gladly...

thx and have a nice weekend

**Comment by Timbuktu1982** [comment]
Hi Jakub.
When do you want to send me the build?
I'm only asking because I'm on holiday next week and won't be able to test again until 07/11.
THX

**Comment by jakubmisek** [comment]
Hi @Timbuktu1982 - sorry for the delay; we're actually not sure what to look for exactly at this moment! I'll try to prepare some logging so we'll move forward.

**Comment by Timbuktu1982** [comment]
Hi Jakub,
ok, thank you.
Do you need more information about my system configuration?

A general question: vscode tracks changes via watchman?

**Comment by jakubmisek** [comment]
> Hi Jakub, ok, thank you. Do you need more information about my system configuration?

I think I have everything that should matter, thank you.

> A general question: vscode tracks changes via watchman?

AFAIK, vscode provides filesystem watcher API through NodeJS fs (https://nodejs.org/docs/latest/api/fs.html)  which uses underlying OS API (= it might behave differently on win/unix). It should not be the problem here, since we're updating problems live from changes in the vscode's text editor.

**Comment by Timbuktu1982** [comment]
Hey Jakub,
there is news in the matter?

THX and a good start into new week

**Comment by jakubmisek** [comment]
Hi, thank you for reminding me!

So far we have released an update that fixes a few related issues. If it doesn't help, we will prepare the debug version of the extension.

**Comment by Timbuktu1982** [comment]
Hello Jakub,
yes, I had seen that and I had installed that version right after the release. But it contains no changes for my problem...

**Comment by jakubmisek** [comment]
> no changes for my problem...

sorry for the delay - ok it seems we'll have to prepare that "insight" version of the extension. I'll note it for my next to-do!

Thank you for all the feedback

**Comment by Timbuktu1982** [comment]
Hi Jakub,

the problem unfortunately still exists after the last update...

**Comment by jakubmisek** [comment]
Thank you @Timbuktu1982 for the update - we have tried to change and fix a few related issues, hoping it would help.

We have no clue what to look for actually - would it be possible to do a quick screen share? Otherwise, we'll prepare the "insights" version with tons of diagnostics :)

**Comment by Timbuktu1982** [comment]
Hi Jakub,
unfortunately, the last update did not eliminate the errors...

Here the screenshots...
First I declare a new variable as a boolean. Then I use it as an array and declare a property. Now when I reload the window (I have to do this, otherwise I don't see the corresponding message), I see the warning message as follows:
![grafik](https://user-images.githubusercontent.com/47846931/210223546-b63d28f3-cb1a-498a-ad1c-f8e036f18e43.png)

When i change the initial declaration of the variable to an array, normally the warning message has to be removed. But i must reload the window, so the warning message will be removed...
![grafik](https://user-images.githubusercontent.com/47846931/210223789-087f6150-e442-4432-9461-0c2e0344c6b8.png)

**Comment by Timbuktu1982** [comment]
Jakub?

**Comment by jakubmisek** [comment]
@Timbuktu1982 Thank you for reminding me,

- a quick test: if you introduce a syntax error (like deleting a semi-colon `;`), would it get underlined with a red wave (immediately)?

**Comment by jakubmisek** [comment]
@Timbuktu1982 
one possibility is, our engine internally deadlocks; we have prepared pre-release `1.26.11955` which notifies in VSCode's Console (Help/Toggle Developer Tools/Console) about pending analysis.

> phptools: analysis pending ... 2 file(s).

If there's something like this keeping to appear over and over, it's that. If it's not, we'll try something else.

Thank you for trying that, and sorry for the delays.

**Comment by Timbuktu1982** [comment]
Hi Jakub,
unfortunately, the last update did not eliminate the errors...

**Comment by jakubmisek** [comment]
Thank you @Timbuktu1982 

We're making some feature updates now, and I'll get back to this issue soon. We're still looking into it.

**Comment by Timbuktu1982** [comment]
Hi Jakub,
thx.
I have installed the last update today. But nothing has changed or I even get an error in the console after the last update (see https://github.com/DEVSENSE/phptools-docs/issues/249).

**Comment by Timbuktu1982** [comment]
Hi Jakub,
thx.
I have installed the last update today. But nothing has changed...

**Comment by frkinta** [comment]
Same issue here.

Classes highlighted here used to have a constructor. They are no more needed and have been deleted since many days and are still highlighted after multiple window reload

![image](https://user-images.githubusercontent.com/20577647/215831020-28d34fdd-e149-4301-957c-20680cdd700f.png)

**Comment by jakubmisek** [comment]
@Timbuktu1982 thank you for testing the update;

We're running out of options here

- Is this bug happening even in a smaller/different workspace?

I'll try the "include path" feature, if it may cause freezing of the vscode problems.

**Comment by Timbuktu1982** [comment]
Hi Jakub,
yes, that is the reason: When i remove the "php.workspace.includePath", the renewal is directly working. But the feature to include more pathes to workspace is a very useful feature...

**Comment by jakubmisek** [comment]
@Timbuktu1982 awesome! I'm happy we know what's causing this.

I'll try to repro the issue locally, and review the includePath feature.

**Comment by Timbuktu1982** [comment]
Thx

**Comment by jakubmisek** [comment]
@Timbuktu1982 isn't the includePath (`file:///var/www/html/flex-container`) overlapping with your project path?

By purpose, we suppress diagnostics from files within the includePath.

**Comment by Timbuktu1982** [comment]
Hi Jakub,
only for the project "flex-container" i can understand this. All other projects are not in the same path or do not overlap with this path.

Here is a example structure:
/var/www/html/flex-container
/var/www/html/flex-container-plugins/.....

If I deactivate the include path in the global settings, everything works.
If I activate the "php.workspace.includePath": "/var/www/html/flex-container;" in the WORKSPACE settings (not in the global settings) of a project in "/var/www/html/flex-container-plugins/", nothing works anymore.

**Comment by Timbuktu1982** [comment]
Jakub, it works :-) :-) :-)

Great. After the last update this morning (in Germany :-)) it works perfectly...

Thank you so much!

**Comment by jakubmisek** [comment]
Oliver, I'm so happy to hear that!

Great it works now, and thank You for your patience! :-)

**Comment by Timbuktu1982** [comment]
Great tool. Very much like
