### ISSUE TITLE
Bogus error "Cannot implicitly convert 'void' to 'string'"

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#748]
I'm getting this bogus error in the IDE from this fragment of code:

![image](https://github.com/user-attachments/assets/3e702574-f865-4ef5-bb76-ddd3a11871bc)

![image](https://github.com/user-attachments/assets/3915c8bc-cb0e-481b-afef-0db14b221124)

```
"Cannot implicitly convert 'void' to 'string'"
```
In reality the code runs and always works as expected.

Even if I replace the first line:
```
$codes = $this->getNewPromoCodes($n);
```
with this:
```
$codes = [];
```
which means that the body of the `foreach` loop would never run, I still get the error!!

I have not been able to reproduce with minimal code.

I tried this which is very close to the real-life code:

```
<?php

function getNewPromoCodes($n = 1) {
    $codes = [];
    for ($i = 0; $i < 1000 && count($codes) < $n; $i++) {
        $new_codes = [];
        for ($k = 0; $k < $n - count($codes); $k++) {
            $newcode = generateRandomPromoCode();
            if (in_array($newcode, $codes)) continue;
            $new_codes[$newcode] = true;
        }
        $existing = [];
        foreach($existing as $ecode) {
            unset($new_codes[$ecode['code']]);
        }
        $codes = array_merge($codes, array_keys($new_codes));
    }
    return $codes;
}

function generateRandomPromoCode() {
    return uniqid();
}

$codes = getNewPromoCodes($n);

$outputs = ["Here are the new promo codes:\n"];
$k = 0;
foreach ($codes as $code) {
    if ($k > 20) {
        $outputs[] = "";
        $k = 0;
    }
    $output = &$outputs[count($outputs) - 1];
    $output .= "\npromo" . str_replace("_", "\\_", $code);
    $output .= "\n```\n/start promo$code\n```\n";
    $k ++;
}
```
but this does _not_ reproduce.

**Comment by php4fan** [comment]
I have found a minimal example that **reproduces the issue**:

```
<?php

class TestClass {
    public function doTest() {
        $codes = [];

        foreach ($codes as $code) {
            echo "Foo bar $code";
        }
    }
}
```

The exact same code **outside of a class method does _not_ reproduce**:

```
$codes = [];

foreach ($codes as $code) {
    echo "Foo bar $code";
}

```

**Comment by jakubmisek** [comment]
@php4fan thank you for the test case. I think this is regression.

**Comment by php4fan** [comment]
Still getting this annoying issue.

**Comment by jakubmisek** [comment]
@php4fan thank you for reminding me.

We'll suppress the warning.

What's the return value of `$this->getNewPromoCodes()` ? It looks like the editor thinks it returns an empty array.

**Comment by php4fan** [comment]
It can very well return an empty array, but that shouldn't be an issue since in that case the `foreach` loop won't run at all.

When it's not empty, it's an array of strings.



This is the code:
```
public function getNewPromoCodes($n = 1) {
        $codes = [];
        for ($i = 0; $i < 1000 && count($codes) < $n; $i++) {
            $new_codes = [];
            for ($k = 0; $k < $n - count($codes); $k++) {
                $newcode = $this->generateRandomPromoCode();
                if (in_array($newcode, $codes)) continue;
                $new_codes[$newcode] = true;
            }
            $existing = $this->query_all(
                "
                    SELECT * FROM `{BOT_TABLE}promo_code`
                    WHERE code IN(:codes)
                ", 
                ['codes' => array_keys($new_codes)],
                ['codes' => Connection::PARAM_STR_ARRAY]
            );
            foreach($existing as $ecode) {
                unset($new_codes[$ecode['code']]);
            }
            $codes = array_merge($codes, array_keys($new_codes));
        }
        return $codes;
    }

    public function generateRandomPromoCode() {
        $chars = "abcdefghijklmnop" .
                 "qrstuvwxyzABCDEF" .
                 "GHIJKLMNOPQRSTUV" .
                 "WXYZ0123456789-_";
        $output = "";
        for ($i = 0; $i < 16; $i++) {
            $output .= $chars[random_int(0, 63)];
        }
        return $output;
    }
```

`$this->query_all()` is a wrapper around `Doctrine\DBAL\Connection::fetchAllAssociative()`.

**Comment by jakubmisek** [comment]
Thank you for pointing this out.

The void->string warning has been fixed.

I think the cause of most of these issues is the `array` sometimes being treated as empty `[]`, which causes `foreach` to iterate over `void` values (doesn't matter - it's our problem).

In general a doc comment like /** @return string[] */ or return type hint would help a lot.

**Comment by jackskaret-aimclear** [comment]
I'm building a WordPress plugin and receiving a lot of this error, specifically when trying to use ACF functions. I installed the acf stubs:

![Image](https://github.com/user-attachments/assets/af3b6737-5b26-490f-9ab4-b39145519c37)

and added to the include path:

![Image](https://github.com/user-attachments/assets/b2d6cd1b-5b2c-426d-8fb9-775cfc017977)

but still receiving this:

![Image](https://github.com/user-attachments/assets/ef53efd2-2f18-4112-b5b2-398138cc6d6a)

When I "Go to definition" or "Peek definition" I see the correct definition, so where is it pulling the incorrect one from?

Is there a way to re-index the definitions?

**Comment by jakubmisek** [comment]
@jackskaret-aimclear it looks like we don't recognize the `@return` annotation (because the author of those stubs uses incorrect `/*` comment type, it should be `/**`)

**Comment by jackskaret-aimclear** [comment]
Thank you! That fixed it.

RE:includePath - I figured it wasn't necessary, just a troubleshooting step.

**Comment by jakubmisek** [comment]
@jackskaret-aimclear maybe we should give pull request to https://github.com/kimhf/advanced-custom-fields-stubs/blob/c3b34a01faf724aeb29d62620fb328f420a2f851/advanced-custom-fields-stubs.php#L14112 to change `/*` to `/**`
